export function getBaseUrl() {
    // Check if we're in a browser environment
    if (typeof window !== "undefined") {
        return window.location.origin;
    }

    // Check if we're in a production environment
    const isProduction = process.env.NODE_ENV === "production";

    if (isProduction) {
        // Priority order for production URLs

        // 1. Custom domain (recommended)
        if (process.env.NEXT_PUBLIC_APP_URL) {
            return process.env.NEXT_PUBLIC_APP_URL;
        }

        // 2. Vercel autogenerated URL
        if (process.env.VERCEL_URL) {
            return `https://${process.env.VERCEL_URL}`;
        }

        // 3. Vercel project production URL
        if (process.env.VERCEL_PROJECT_PRODUCTION_URL) {
            return `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`;
        }

        // 4. Fallback (should be avoided in real production)
        throw new Error(
            "No production URL configured. Please set NEXT_PUBLIC_APP_URL environment variable."
        );
    }

    // Default for local development
    return "http://localhost:3000";
}
